export const SIGNUP_USER = "SIGNUP_USER";
export const SET_LOGIN_USER = "SET_LOGIN_USER";
export const RESET_LOGIN_USER = "RESET_LOGIN_USER";

//City Weather
export const FETCH_CITY_WEATHER = "FETCH_CITY_WEATHER";
export const RESET_CITY = "RESET_CITY";
export const FETCH_LOCATION_CORDINATES = "FETCH_LOCATION_CORDINATES";
export const RESET_LOCATION_CORDINATES = "RESET_LOCATION_CORDINATES";
export const SHOW_CITY_HISTORY = "SHOW_CITY_HISTORY";
